version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    env_file: ./.env
    ports:
      - 1433:1433
    volumes:
      - .\data:/var/opt/mssql/data
