name: SQL for GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
    build:
        runs-on: windows-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Login via Az module
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Azure SQL Deploy
          uses: azure/sql-action@v1
          with:
            server-name: ads-demo-server.database.windows.net
            connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
            dacpac-package: './db/db_project/DatabaseProjectsales/bin/Debug/DatabaseProjectsales.dacpac'

        # Azure logout 
        - name: logout
          run: |
            az logout

